name: 'Deploy Kubernetes Cluster'
run-name: 'Deploy Kubernetes Cluster'
on: [push]
jobs:
  kubernetes-cluster:
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Github Actions checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.POOL_ID }}/providers/${{ vars.PROVIDER_ID }}'
          service_account: '${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
