# TODO turn this into a reusable action/module
name: 'Terraform Apply'
run-name: 'Terraform Apply'
on: workflow_dispatch 
env:
  CONFIG_DIRECTORY: "./"
jobs:
  infra-plan:
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Github Actions checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ vars.GCP_WIF_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.POOL_ID }}/providers/${{ vars.PROVIDER_ID }}'
          service_account: '${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Run Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/iac/terraform
      - name: Run Terraform Plan
        run: terraform plan
        working-directory: ${{ github.workspace }}/iac/terraform
  infra-apply:
    needs: infra-plan
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Github Actions checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ vars.GCP_WIF_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.POOL_ID }}/providers/${{ vars.PROVIDER_ID }}'
          service_account: '${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Run Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/iac/terraform
      - name: Run Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ github.workspace }}/iac/terraform
